ALL_ASSETS = [
    'ECB/EURPLN',
    'ECB/EURGBP',
    'ECB/EURIDR',
    'ECB/EURKRW',
    'ECB/EURSEK',
    'ECB/EURHKD',
    'ECB/EURRON',
    'ECB/EURCHF',
    'ECB/EURTRY',
    'ECB/EURPHP',
    'ECB/EURZAR',
    'ECB/EURISK',
    'ECB/EURMXN',
    'ECB/EURCZK',
    'ECB/EURNOK',
    'ECB/EURAUD',
    'ECB/EURMYR',
    # 'ECB/EURLTL',
    'ECB/EURINR',
    # 'ECB/EURBGN', #Bulgaria
    'ECB/EURCNY',
    'ECB/EURHUF',
    'ECB/EURJPY',
    'ECB/EURCAD',
    'ECB/EURRUB',
    'ECB/EURBRL',
    'ECB/EURSGD',
    # 'ECB/EURHRK',
    'ECB/EURILS',
    'ECB/EURNZD',
    'ECB/EURTHB',
    'ECB/EURUSD',
    # 'ECB/EURDKK' # Denmark

]