
ALL_ASSETS = [
    'ECB/EURGBP',
    'ECB/EURUSD',
    'ECB/EURJPY',
    'BOE/XUDLJYD',
    'BOE/XUDLJYS',
    'BOE/XUDLUSS'


]

ECB_ASSETS = [
    'ECB/EURPLN',
    'ECB/EURGBP',
    'ECB/EURIDR',
    'ECB/EURKRW',
    'ECB/EURSEK',
    'ECB/EURHKD',
    'ECB/EURRON',
    'ECB/EURCHF',
    'ECB/EURTRY',
    'ECB/EURPHP',
    'ECB/EURZAR',
    'ECB/EURISK',
    'ECB/EURMXN',
    'ECB/EURCZK',
    'ECB/EURNOK',
    'ECB/EURAUD',
    'ECB/EURMYR',
    # 'ECB/EURLTL',
    'ECB/EURINR',
    # 'ECB/EURBGN', #Bulgaria
    'ECB/EURCNY',
    'ECB/EURHUF',
    'ECB/EURJPY',
    'ECB/EURCAD',
    'ECB/EURRUB',
    'ECB/EURBRL',
    'ECB/EURSGD',
    # 'ECB/EURHRK',
    'ECB/EURILS',
    'ECB/EURNZD',
    'ECB/EURTHB',
    'ECB/EURUSD',
    # 'ECB/EURDKK' # Denmark

]



BankOfEngland_ASSETS = [
#Australian Dollar (AUD)',',
#'XUDLADD', -- WHAT
'XUDLADS',
## Canadian Dollar (CAD)',
'XUDLCDD',
'XUDLCDS',
## Chinese Yuan (CNY)',
'XUDLBK73',
'XUDLBK89',
## Czech Koruna (CZK)',
'XUDLBK27',
'XUDLBK25',
# XUDLBK26',
## Danish Krone (DKK)',
'XUDLDKD',
'XUDLDKS',
# XUDLBK76',
## Hong Kong Dollar (HKD)',
'XUDLHDD',
'XUDLHDS',
## Hungarian Forint (HUF)',
'XUDLBK35',
'XUDLBK33',
# XUDLBK34',
# Indian Rupee (INR)',
'XUDLBK64',
'XUDLBK97',
## Israeli Shekel (NIS)',
'XUDLBK65',
'XUDLBK78',
# Japanese Yen (JPY)',
'XUDLJYD',
'XUDLJYS',
# XUDLBK63',
# Lithuanian Litas (LTL)',
# XUDLBK38',
# XUDLBK36',
# XUDLBK37',
# Malaysian Ringgit (MYR)',
'XUDLBK66',
'XUDLBK83',
# New Zealand Dollar (NZD)',
'XUDLNDD',
'XUDLNDS',
# Norwegian Krone (NOK)',
'XUDLNKD',
'XUDLNKS',
# Polish Zloty (PLN)',
'XUDLBK49',
'XUDLBK47',
# XUDLBK48',
# Pound Sterling (GBP)',
'XUDLGBD',
#'XUDLGBG', -- WHAT?
# XUDLSER',
# Russian Ruble (RUB)',
# XUDLBK69',
# XUDLBK85',
# Saudi Riyal (SAR)',
'XUDLSRD',
'XUDLSRS',
# Singapore Dollar (SGD)',
'XUDLSGD',
'XUDLSGS',
# South African Rand (ZAR)',
'XUDLZRD',
'XUDLZRS',
# South Korean Won (KRW)',
'XUDLBK74',
'XUDLBK93',
# Swedish Krona (SEK)',
'XUDLSKD',
'XUDLSKS',
# Swiss Franc (CHF)',
'XUDLSFD',
'XUDLSFS',
# XUDLBK68',
# New Taiwan Dollar (TWD)',
'XUDLTWD',
'XUDLTWS',
# Thai Baht (THB)',
'XUDLBK72',
'XUDLBK87',
# Turkish Lira (TRY)',
'XUDLBK75',
'XUDLBK95'
]


# BOE_ASSETS = ['BOE/'+x for x in BankOfEngland_ASSETS]
# ALL_ASSETS = BOE_ASSETS + ECB_ASSETS